redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://redistogo:34ac1350d9245fce4ee60445a31b6a0f@tarpon.redistogo.com:10180/
development: *redis
test: *redis
