redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://redistogo:2e2f46797d3e619eae9914f5cd324831@tarpon.redistogo.com:10452/
development: *redis
test: *redis
